package com.sklep.services;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;

import com.sklep.project.Client;
import com.sklep.project.Product;
public class ClientDBManager {

	
	private Connection conn;
	private Statement stmt;
	private PreparedStatement addClientStmt;
	
	public ClientDBManager() throws java.sql.SQLException, SQLException
	{
	
		conn= DriverManager.getConnection("jdbc::hsqldb:hsql://localhost/wordbk");
		boolean clientTableExists=false;
		ResultSet rs= conn.getMetaData().getTables(null, null,null, null);
		stmt=conn.createStatement();
		
		
		addClientStmt = conn.prepareStatement(""+
		
		"INSERT INTO client (name) VALUES (?)"+
		"");
		
		while(rs.next()){
			if("Client".equalsIgnoreCase(rs.getString("TABLE_NAME")))
			{clientTableExists=true;
			break;
			}
				
		}
		if(!clientTableExists){
			
		
		stmt.executeUpdate(""+
		
			"CREATE TABLE client("+
			"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"+
			"name varchar(20)."+
			""+
			")");
				
			
		}
		

		
		
	}
	public void addClient(Client c) throws java.sql.SQLException{
		
		addClientStmt.setString(1,c.toString());
		addClientStmt.executeUpdate();
	}	
	
}
