package com.sklep.services;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import com.sklep.project.Client;
import com.sklep.project.Product;

public class ProductDBManager {

	private Connection conn;
	private Statement stmt;
	private PreparedStatement addProductStmt;
	private PreparedStatement getProductStmt;
	private PreparedStatement dropProductStmt;
	
	
	
	public ProductDBManager() throws java.sql.SQLException, SQLException
	{
	
	
	boolean productTableExists=false;
	conn= DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");

	
	ResultSet rs= conn.getMetaData().getTables(null, null,null, null);
	stmt=conn.createStatement();
	
	while(rs.next()){
		if("Product".equalsIgnoreCase(rs.getString("TABLE_NAME")))
		{productTableExists=true;
		break;
		}
		}
	
	
	
	if(!productTableExists)
	{
		
	
		stmt.executeUpdate("" +
				"CREATE TABLE product(" +
				"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
				"name varchar(20)," +
				"price double," +
				"code float," +
				"" +
				")");
			
	}
	
	addProductStmt=conn.prepareStatement("" +
			"INSERT INTO Product (name,price,code) VALUES (?,?,?)" +
			"");
		
	getProductStmt=conn.prepareStatement("" +
			"SELECT * FROM Product" +
			"");
	
	dropProductStmt=conn.prepareStatement("" +
			"DROP TABLE Product" +
			"");
	
	
	}
	
	
	public void addProduct(Product p) throws java.sql.SQLException, SQLException
	{
		addProductStmt.setString(1, p.getName().toString());
		addProductStmt.setDouble(2, p.getPrice());
		addProductStmt.setFloat(3, p.getCode());
		addProductStmt.executeUpdate();

	}
	
	
	public void droptableproduct() throws java.sql.SQLException{
		
		dropProductStmt.executeUpdate();
	}
	
	
	
	
	
	
	
	
	
	
	
	
}
